# Generated by Django 4.1.4 on 2023-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='request',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
